// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package controller

import (
	"context"
	"main/internal/auth/repository"
	"main/internal/auth/service"
	"main/pkg/db/postgres"
)

// Injectors from wire.go:

func Wire(ctx context.Context, db *postgres.DbCluster) *Controller {
	repositoryRepository := repository.NewRepository(db)
	serviceService := service.NewService(repositoryRepository)
	controller := NewController(serviceService)
	return controller
}
