// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package controller

import (
	"context"
	repository2 "main/internal/auth/repository"
	"main/internal/auth/service"
	repository6 "main/internal/bill/repository"
	service5 "main/internal/bill/service"
	repository4 "main/internal/group/repository"
	service6 "main/internal/group/service"
	repository5 "main/internal/group_permission/repository"
	service4 "main/internal/group_permission/service"
	repository3 "main/internal/otp/repository"
	service2 "main/internal/otp/service"
	"main/internal/user/repository"
	service3 "main/internal/user/service"
	"main/pkg/db/postgres"
)

// Injectors from wire.go:

func Wire(ctx context.Context, db *postgres.DbCluster) *Controller {
	repositoryRepository := repository.NewRepository(db)
	repository7 := repository2.NewRepository(db)
	serviceService := service.NewService(repository7)
	repository8 := repository3.NewRepository(db)
	service7 := service2.NewService(repository8)
	service8 := service3.NewService(repositoryRepository, serviceService, service7)
	repository9 := repository4.NewRepository(db)
	repository10 := repository5.NewRepository(db)
	service9 := service4.NewService(repository10)
	repository11 := repository6.NewRepository(db)
	service10 := service5.NewService(repository11)
	service11 := service6.NewService(repository9, service9, service10)
	controller := NewController(service8, service11)
	return controller
}
