// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"context"
	"main/internal/group/repository"
	repository2 "main/internal/group_permission/repository"
	"main/internal/group_permission/service"
	"main/pkg/db/postgres"
)

// Injectors from wire.go:

func Wire(ctx context.Context, db *postgres.DbCluster) *Service {
	repositoryRepository := repository.NewRepository(db)
	repository3 := repository2.NewRepository(db)
	serviceService := service.NewService(repository3)
	service2 := NewService(repositoryRepository, serviceService)
	return service2
}
