// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"context"
	"main/internal/group_permission/repository"
	"main/pkg/db/postgres"
)

// Injectors from wire.go:

func Wire(ctx context.Context, db *postgres.DbCluster) *Service {
	repositoryRepository := repository.NewRepository(db)
	service := NewService(repositoryRepository)
	return service
}
